---
# tasks file for postgres
# Install postgresql
- apt: name=postgresql-9.5
- pip: name=psycopg2

- name: setup pg_hba.conf
  template:
    src=pg_hba.conf.j2
    dest=/etc/postgresql/9.5/main/pg_hba.conf
    owner=postgres
  register: pg_hba
  sudo: yes